/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
 import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
 import eicVersions from "./docs/eic/versions.json";

 import {
   versionCrumb,
   versionSelector,
 } from "docusaurus-plugin-openapi-docs/lib/sidebars/utils";
 
import eic_5_0_Sidebar from "./docs/eic/sidebar";

 const sidebars: SidebarsConfig = {
  "eic-5.0": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(eicVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb(`v5.0`),
    },
    {
      type: "category",
      label: "EIC",
      link: {
        type: "generated-index",
        title: "v5.0 (latest)",
        description:
          "This is a Saviynt EIC API Spec for V2.0.  For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/api-reference/rest/5.0",
      },
      items: eic_5_0_Sidebar,
    },
  ],
  "connectors": [
    {type: 'autogenerated', dirName: '.'}
  ],
  "Extensions": [
    {type: 'autogenerated', dirName: '.'}
  ]
 };
 
 export default sidebars;
 