name: Blog Discussion Creator
on:
  push:
    paths:
      - 'blog/**'
jobs:
  create-discussion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create GitHub Discussion
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:owner/:repo/discussions
          title: ${{ env.BLOG_TITLE }}
          body: ${{ env.BLOG_URL }}
          category_id: ${{ env.CATEGORY_ID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BLOG_TITLE: 'Extract from blog metadata'
          BLOG_URL: 'Extract and construct the URL'
          CATEGORY_ID: 'Your category ID here'
